/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.iiordanov.wiktionarylookup.WikiDici;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int dictionary=0x7f020000;
        public static final int wotd=0x7f020001;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f060002;
        public static final int layout=0x7f060000;
        public static final int lookup_button=0x7f060004;
        public static final int lookup_text=0x7f060003;
        public static final int webview=0x7f060001;
        public static final int word_suggest_row_text=0x7f060005;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int word_suggest_row=0x7f030001;
    }
    public static final class raw {
        public static final int index=0x7f040000;
        public static final int searching=0x7f040001;
        public static final int wiki_css=0x7f040002;
        public static final int wiki_page_template=0x7f040003;
        public static final int word_not_found=0x7f040004;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int lookup=0x7f050001;
        public static final int word_not_found=0x7f050002;
        public static final int wotd=0x7f050003;
    }
}
